global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'elite-decision-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi-backend'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']

  - job_name: 'postgres-db'
    static_configs:
      - targets: ['db:5432'] # Setup for future postgres_exporter inclusion
