"""Add ForeignKey constraints batch

Revision ID: d6b883caef44
Revises: afc7da2f5a99
Create Date: 2026-07-25 03:20:26.726790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b883caef44'
down_revision: Union[str, Sequence[str], None] = 'afc7da2f5a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_explanations', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_decision_explanations_signal_id', 'signals', ['signal_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_journal_entries_trade_id', 'trades', ['trade_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_journal_entries_signal_id', 'signals', ['signal_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_notifications_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_paper_orders_trade_id', 'trades', ['trade_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_paper_trades_position_id', 'trades', ['position_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_paper_trades_order_id', 'paper_orders', ['order_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_trades_signal_id', 'signals', ['signal_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_settings_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_watchlists_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('decision_explanations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
