"""add trade user_id

Revision ID: 07abfb09709a
Revises: 880c73197822
Create Date: 2026-08-14 22:14:31.207109

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '07abfb09709a'
down_revision: str | Sequence[str] | None = '880c73197822'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_column('trades', 'user_id')
    # ### end Alembic commands ###
