"""add paper order and paper trade user_id

Revision ID: 09ce272083f9
Revises: 56e119130954
Create Date: 2026-08-14 22:33:11.672748

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '09ce272083f9'
down_revision: str | Sequence[str] | None = '56e119130954'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_paper_orders_user_id'), 'paper_orders', ['user_id'], unique=False)
    op.add_column('paper_trades', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_paper_trades_user_id'), 'paper_trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trades_user_id'), table_name='paper_trades')
    op.drop_column('paper_trades', 'user_id')
    op.drop_index(op.f('ix_paper_orders_user_id'), table_name='paper_orders')
    op.drop_column('paper_orders', 'user_id')
    # ### end Alembic commands ###
