"""add journal entry user_id

Revision ID: 56e119130954
Revises: 07abfb09709a
Create Date: 2026-08-14 22:20:11.089971

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56e119130954'
down_revision: str | Sequence[str] | None = '07abfb09709a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_column('journal_entries', 'user_id')
    # ### end Alembic commands ###
