"""add signal user_id

Revision ID: 880c73197822
Revises: 9c1e27b54203
Create Date: 2026-08-14 22:07:00.652268

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '880c73197822'
down_revision: str | Sequence[str] | None = '9c1e27b54203'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_signals_user_id'), 'signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_user_id'), table_name='signals')
    op.drop_column('signals', 'user_id')
    # ### end Alembic commands ###
