"""add signal retry_count and next_retry_at

Revision ID: af34892835f3
Revises: 09ce272083f9
Create Date: 2026-08-15 18:55:06.402657

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af34892835f3'
down_revision: str | Sequence[str] | None = '09ce272083f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here (unlike the nullable=True user_id
    # migrations) -- retry_count is NOT NULL, so existing rows need a real
    # value to backfill against, not just a Python-side ORM default.
    op.add_column('signals', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('signals', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'next_retry_at')
    op.drop_column('signals', 'retry_count')
    # ### end Alembic commands ###
